import Head from 'next/head'

// components
import ContactForm from "../components/ContactForm/ContactForm";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Forms with netlify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <ContactForm />
      
    </div>
  )
}

